print ()
print ("Assignment #1")
print ()
print ("1. Twinkle, twinkle, little star,")
print ("        How I wonder what you are!")
print ("                Up above the world so high,")
print ("                Like a diamond in the sky.")
print ("   Twinkle, twinkle, little star,")
print ("        How I wonder what you are!")
print ()
print ()
print ("2. PUP Hymns, Mission and Vision")
print ()
print ("              Imno ng PUP")
print ("    S. Calabig, S. Roldan, and R. Amaranto")
print ()
print ("    Sintang Paaralan")
print ("    Tanglaw ka ng bayan")
print ("    Pandayan ng isip ng kabataan")
print ("    Kami ay dumating nang salat sa yaman")
print ("    Hanap na dunong ay iyong alay")
print ("    Ang layunin mong makatao")
print ("    Dinarangal ang Pilipino")
print ("    Ang iyong aral, diwa, adhikaing taglay")
print ("    PUP, aming gabay")
print ("    Paaralang dakila")
print ("    PUP, pinagpala")
print ("    Gagamitin ang karunungan")
print ("    Mula sa iyo, para sa bayan")
print ("    Ang iyong aral, diwa, adhikaing taglay")
print ("    PUP, aming gabay")
print ("    Paaralang dakila")
print ("    PUP, pinagpala")
print ()
print ()
print ("              PCC Hymn")
print ()
print ("    Oh! PCC thy glorious name")
print ("    A symbol we'll uphold")
print ("    Forever we will follow on")
print ("    The light that guides us all")
print ("    The beacon light has led us through")
print ("    To strive for dignity")
print ("    We'll stand and fight for PCC")
print ("    To keep her name unowned")
print ("    Dear Alma Mater may your brow")
print ("    With Laurels ever crowned")
print ("    All hail the flag of PCC")
print ("    In bright maroon and gold")
print ("    The colors bright for loyalty")
print ("    For service keep unfurled")
print ("    The honors we have always won")
print ("    Shalt live forever on")
print ("    For loyal sons and daughters")
print ("    of our dear PCC")
print ("    Forever thee we'll honor")
print ("    and serve with loyalty.")
print ()
print ()
print ("            PUP Imno Sentenyal")
print ("    Paceli S. Eugenio and Antonio R. Regalario")
print ()
print ("    Sandaang taon ng iyong kasaysayan")
print ("    Mula sa abang karukhaang kinagisnan")
print ("    Sa hirap at pagdurusang sakdal labis")
print ("    Nagtiis at di nawalan ng pag-asa")
print ("    Sa puso, sa diwa ay nagtanim ng pangarap.")
print ()
print ("    Sanlaksang pagsubok binaka")
print ("    Nakipagtunggali sa mga unos ng buhay")
print ("    Ika'y bumangon, nakibaka't nagtagumpay")
print ("    Nakamtan ang hangad na dangal")
print ("    Para malayang ikampay")
print ("    Kalayaang bumukal sa kaluluwa ng kabayanihan.")
print ()
print ("    Sandaang taon iyong kasaysayan")
print ("    Maningning kang bantayog ng kagitingan")
print ("    Luningning ka ng kadakilaan")
print ("    Ilaw ng kaisipan ng Kapilipinuhan")
print ("    Nagpupugay kami sa iyo")
print ("    Pag-asa ka ng bayan.")
print ()
print ("    Dakila ka PUP, sa diwa mong makabayan")
print ("    Sa kaluluwa mong maka-Diyos")
print ("    Dakila kang totoo.")
print ()
print ("    PUP, manguna ka")
print ("    Sa husay, sa laya't katarungan")
print ("    Alay sa dukhang Pilipino")
print ("    Mabuhay ka, magpakailanman")
print ()
print ("    PUP, mabuhay ka!")
print ()
print ()
print ("         Vision")
print ()
print ("    A Leading")
print ("    Comprehensive")
print ("    Polytechnic")
print ("    University in Asia")
print ()
print ()
print ("         Mission")
print ()
print ("    Advance An Inclusive")
print ("    Equitable, And Globally")
print ("    Relevant Polytechnic")
print ("    Education Towards")
print ("    National Development")
print ()
print ()
print ("3.  Golden Lyrics")
print ()
print ("            Golden")
print ("    Ejae, Audrey Nuna, Rei Ami")
print ()
print ("    I was a ghost, I was alone")
print ("    Eoduwojin apgilsoge (Hah)")
print ("    Given the throne, I didn't know how to believe")
print ("    I was the queen that I'm meant to be")
print ("    I lived two lives, tried to play both sides")
print ("    But I couldn't find my own place")
print ("    Called a problem child 'cause I got too wild")
print ("    But now that's how I'm getting paid, kkeuteopsi on stage")
print ()
print ("    I'm done hidin', now I'm shinin'")
print ("    Like I'm born to be")
print ("    We dreamin' hard, we came so far")
print ("    Now I believe")
print ()
print ("    We're goin' up, up, up")
print ("    It's our moment")
print ("    You know together we're glowing")
print ("    Gonna be, gonna be goldеn")
print ("    Oh, up, up, up")
print ("    With our voices")
print ("    Yeongwonhi kkaejil su еomneun")
print ("    Gonna be, gonna be golden")
print ()
print ("    Oh, I'm done hidin' now I'm shinin'")
print ("    Like I'm born to be")
print ("    Oh, our time, no fears, no lies")
print ("    That's who we're born to be")
print ()
print ("    Waited so long to break these walls down")
print ("    To wake up and feel like me")
print ("    Put these patterns all in the past now")
print ("    And finally live like the girl they all see")
print ()
print ("    No more hiding, I'll be shining")
print ("    Like I'm born to be")
print ("    'Cause we are hunters, voices strong")
print ("    And I know I believe")
print ()
print ("    We're goin' up, up, up")
print ("    It's our moment")
print ("    You know together we're glowing")
print ("    Gonna be, gonna be goldеn")
print ("    Oh, up, up, up")
print ("    With our voices")
print ("    Yeongwonhi kkaejil su еomneun")
print ("    Gonna be, gonna be golden")
print ()
print ("    Oh, I'm done hidin', now I'm shinin'")
print ("    Like I'm born to be")
print ("    Oh, our time, no fears, no lies")
print ("    That's who we're born to be")
print ()
print ("    You know we're gonna be, gonna be golden (Oh)")
print ("    We're gonna be, gonna be (Oh)")
print ("    Born to be, born to be glowin' (Oh)")
print ("    Balkge bitnaneun urin")
print ("    You know that it's our time, no fears, no lies (Oh, oh)")
print ("    That's who we're born to be")
print ()
print ()
print ("4. Lupang Hinirang")
print ()
print ("            Lupang Hinirang")
print ("    National Anthem of the Philippines")
print ()
print ("    Bayang magiliw")
print ("    Perlas ng Silanganan")
print ("    Alab ng puso")
print ("    Sa dibdib mo'y buhay")
print ()
print ("    Lupang Hinirang")
print ("    Duyan ka ng magiting")
print ("    Sa manlulupig")
print ("    'Di ka pasisiil")
print ()
print ("    Sa dagat at bundok")
print ("    Sa simoy at sa langit mong bughaw")
print ("    May dilag ang tula")
print ("    At awit sa paglayang minamahal")
print ()
print ("    Ang kislap ng watawat mo'y")
print ("    Tagumpay na nagniningning")
print ("    Ang bituin at araw niya")
print ("    Kailan pa ma'y 'di magdidilim")
print ()
print ("    Lupa ng araw ng luwalhati't pagsinta")
print ("    Buhay ay langit sa piling mo")
print ("    Aming ligaya na 'pag may mang-aapi")
print ("    Ang mamatay ng dahil sa iyo")