print ()
print ("Assignment #2\n")

print ("1. Resume\n")

print ("\033[1mPersonal Background Section\033[0m")
firstName = input("Enter your first name: ")
lastName = input("Enter your last name: ")
age = int(input("Enter your age: "))
your_email = input("Enter your email address: ")
your_contact = input("Enter your contact number: ")
date_of_birth = input("Enter your date of birth: ")
place_of_birth = input("Enter your place of birth: ")
nationality = input("Enter your nationality: ")
print ()

print ("\033[1mEducational Background Section\033[0m\n")

print ("\033[1mCollege\033[0m")
college_date = input("Enter year: ")
college_university = input("Enter your university: ")
course = input("Enter your course: ")
print ()

print ("\033[1mSenior High School\033[0m")
shs_date = input("Enter year: ")
shs_university = input("Enter your university: ")
strand = input("Enter your strand: ")
print ()

print ("\033[1mJunior High School\033[0m")
jhs_date = input("Enter year: ")
school = input("Enter your school: ")
print ()

print ("\033[1mObjectives\033[0m")
objectives = input("Enter your objectives: ")
print ()

print ("\033[1mSkills\033[0m")
my_skills = []
for i in range(5):
    skills = input(f"Enter your skill #{i+1}: ")
    my_skills.append(skills)
print ()

print ("\033[1mAchievements\033[0m")
my_achievements = []
for i in range(5):
    achievements = input(f"Enter your achievements #{i+1}: ")
    my_achievements.append(achievements)
print ()

print ("\033[1mCharacter References\033[0m")
referrer1 = input(f"Enter name of referrer: ")
relationship1 = input("Enter relationship with them: ")
referrer1_contact = input("Enter their contact number: ")
referrer1_email = input("Enter their email address: ")
print ()
referrer2 = input(f"Enter name of referrer: ")
relationship2 = input("Enter relationship with them: ")
referrer2_contact = input("Enter their contact number: ")
referrer2_email = input("Enter their email address: ")
print ()
referrer3 = input(f"Enter name of referrer: ")
relationship3 = input("Enter relationship with them: ")
referrer3_contact = input("Enter their contact number: ")
referrer3_email = input("Enter their email address: ")
print ()

print (print ("\033[1mResume\033[0m"))
print ()
print ("\033[1mPersonal Background Section\033[0m")
print (f"Name: {lastName}, {firstName}\nAge: {age}\nEmai: {your_email}\nContact Number: {your_contact}")
print (f"Date of Birth: {date_of_birth}\nPlace of Birth: {place_of_birth}\nNationality: {nationality}\n")
print ("\033[1mEducational Background Section\033[0m")
print ()
print ("\033[1mCollege\033[0m")
print (f"Date: {college_date}\nUniversity: {college_university}\nCourse: {course}")
print ()
print ("\033[1mSenior High School\033[0m")
print (f"Date: {shs_date}\nUniversity: {shs_university}\nStrand: {strand}")
print ()
print ("\033[1mJunior High School\033[0m")
print (f"Date: {jhs_date}\nSchool: {school}")
print ()
print ("\033[1mObjectives Section\033[0m")
print (f"Objectives: {objectives}")
print ()
print ("\033[1mSkills Section\033[0m")
for i, skill in enumerate(my_skills):
    print(f"Skill {i+1}: {skill}")
print ()
print ("\033[1mAchievements Section\033[0m")
for i, achievement in enumerate(my_achievements):
    print(f"Achievement {i+1}: {achievement}")
print ()
print ("\033[1mCharacter References Section\033[0m")
print (f"1. Name: {referrer1}")
print (f"   Relationship: {relationship1}")
print (f"   Contact Number: {referrer1_contact}")
print (f"   Email Address: {referrer1_email}")
print ()
print (f"2. Name: {referrer2}")
print (f"   Relationship: {relationship2}")
print (f"   Contact Number: {referrer2_contact}")
print (f"   Email Address: {referrer2_email}")
print ()
print (f"3. Name: {referrer3}")
print (f"   Relationship: {relationship3}")
print (f"   Contact Number: {referrer3_contact}")
print (f"   Email Address: {referrer3_email}")





